from enum import Enum

class Message(Enum):
    # Setup
    SETUP_FIRST_STEP = "Please press the blue button."
    SETUP_SECOND_STEP = "Home ROBOT"
    ENTER_ID_AND_PASSWORD = "Enter id and password IN BULGARIAN"
    INVALID_LOGIN_ID = "Invalid ID"
    SCAN_QR_TO_LOGIN = "Scan QR Code to Login"
    INCORRECT_PASSWORD = "Incorrect password."
    USER_NOT_FOUND = "User not found."

    # Login
    NEXT = "Next"
    PASSWORD = "PASSWORD"
    ID = "ID"
    LOGIN = "Login"
    HOME_ROBOT = "Home Robot"
    BACK = "BACK"
    ERROR_HOMING = "ERROR HOMING"
    USER = "USER"
    FIRST_NAME = "FIRST NAME"
    LAST_NAME = "LAST NAME"
    ROLE = "ROLE"
    LOGIN_TIME = "LOGIN TIME"
    SESSION_DURATION = "SESSION DURATION"

    # Main Window
    WORK = "Work"
    SERVICE = "Service"
    ADMINISTRATION = "Administration"
    STATISTICS = "Statistics"

    # User Management
    UNKNOWN = "Unknown"
    ADD_USER = "Add User"
    EDIT_USER = "Edit User"
    DELETE_USER = "Delete User"
    REFRESH = "Refresh"
    READY = "Ready"
    GENERATE_QR = "Generate QR"
    LOADED = "Loaded"
    ERROR_LOADING_USERS = "Error loading users"
    ADD_NEW_USER = "Add New User"
    ADDED_SUCCESSFULLY = "added successfully"
    UPDATED_SUCCESSFULLY = "updated successfully"
    UPDATED_DELETED = "deleted successfully"
    USER_ALREADY_EXISTS = "User already exists"
    USERS_FOUND = "users found"
    ERROR_ADDING_USER = "Error adding user"
    ERROR_UPDATING_USER = "Error updating user"
    ERROR_DELETING_USER = "Error deleting user"
    ERROR_APPYING_FILTER = "Error applying filter"
    PLEASE_SELECT_USER_TO_EDIT = "Please select a user to edit"
    PLEASE_SELECT_USER_TO_DELETE = "Please select a user to delete"
    PLEASE_SELECT_USER_TO_GENERATE_QR_CODE = "Please select a user to generate a QR code"
    CONFIRM_DELETE = "Confirm Delete"
    ARE_YOU_SURE_YOU_WANT_TO_DELETE_USER = "Are you sure you want to delete user"
    SAVE = "Save"
    CANCEL = "Cancel"
    ID_MUST_BE_VALID_NUMBER = "ID must be a valid number"
    ALL_FIELDS_ARE_REQUIRED = "All fields are required"
    USER_MANAGEMENT = "User Management"
    FILTER_USERS = "Filter Users"
    FILTER_BY = "Filter by"
    FILTER_APPLIED = "Filter applied"
    ALL = "All"
    ERROR = "Error"
    QR_CODE = "QR Code"
    INFORMATION = "Information"
    ENTER_FILTER_VALUE = "Enter filter value..."
    APPLY_FILTERS = "Apply Filter"
    CLEAR_FILTERS = "Clear Filter"

    # Glue Meter Card
    ENTER_G_PER_M = "Enter g/m"
    ENTER_G_PER_SQUARE_M = "Enter g/m²"

    # Gallery
    SELECT_DATE_RANGE = "Select Date Range"
    FROM = "From"
    TO = "To"

    # Glue Settings View
    SPRAY_SETTINGS = "Spray Settings"
    SPRAY_WIDTH = "Spray Width"
    SPRAYING_HEIGHT = "Spraying Height"
    FAN_SPEED = "Fan Speed"
    GENERATOR_TO_GLUE_DELAY = "Generator to Glue Delay"
    MOTOR_SETTINGS = "Motor Settings"
    MOTOR_SPEED = "Motor Speed"
    REVERSE_STEPS = "Reverse Steps"
    REVERSE_DURATION = "Reverse Duration"
    REVERSE_SPEED = "Reverse Speed"
    GENERAL_SETTINGS = "General Settings"
    RZ_ANGLE = "RZ Angle"
    GLUE_TYPE = "Glue Type"
    DEVICE_CONTROL = "Device Control"
    MOTOR_CONTROL = "Motor Control"
    RELAY_CONTROL = "Relay Control"
    RELAY = "Relay"
    OTHER_SETTINGS = "Other Settings"
    GENERATOR = "Generator"
    FAN = "Fan"
    MOTOR = "Motor"
    DISPENSE_GLUE = "Dispense Glue"
    GENERATOR_TIMEOUT = "Generator Timeout"
